#!/bin/bash
BASE_DIR="/Users/priyom_saha/Documents/racecar-aggregator"
source "$BASE_DIR/venv/bin/activate"
echo "Using Python: $(which python)"
python "/Users/priyom_saha/Documents/racecar-aggregator/Run.py" "$@"
read -p "Press enter to exit..."
